name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - v4
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Debug Submodule Info
        run: |
          echo "Current directory: $(pwd)"
          echo "Submodule status:"
          git submodule status
          echo "Git modules config:"
          cat .gitmodules
          echo "Git config:"
          git config --list
          echo "Testing submodule URL access:"
          git ls-remote https://github.com/kimturing/content.git
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
          token: ${{ secrets.PAT }}
          submodules: true  # Fetch submodules
          recursive: true   # Recursively fetch submodules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
